version: '3.9'

services:
  spamhouse:
    image: spamhouse:latest
    container_name: spamhouse
    # build:  
    #   context: .
    #   target: test
    #command: ["run", "main.go"]
    # entrypoint: "ls"
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      - DATA_SOURCE_NAME=/var/lib/sqlite/data/spamhouse.db
      - LOG_LEVEL=debug
      - SERVER_PORT=${PORT:-8080}
    networks:
      - spamhouse-network
    volumes:
      - data:/var/lib/sqlite/data
    command: 
      - /bin/sh
      - -c
      - /usr/local/bin/spamhouse
  test:
    container_name: spamhouse-test
    image: spamhouse-test:latest
    environment: 
      - DATA_SOURCE_NAME=/var/lib/sqlite/data/spamhouse.db
      - LOG_LEVEL=debug
    volumes:
      - data:/var/lib/sqlite/data
    networks:
      - spamhouse-network
    depends_on: 
      - spamhouse
    command:
      - /bin/sh
      - -c 
      - go test --tags=integration -v ./...

volumes:
  data:
    name: spamhouse-data

networks:
  spamhouse-network:
    name: spamhouse-network
