version: '3.9'

services:
  spamhouse:
    image: spamhouse:latest
    container_name: spamhouse
    # build:  
    #   context: .
    #   target: test
    #command: ["run", "main.go"]
    # entrypoint: "ls"
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATA_SOURCE_NAME=/var/lib/sqlite/data/spamhouse.db
      - LOG_LEVEL=debug
      - PORT=${PORT}
    volumes:
      - data:/var/lib/sqlite/data
    command: 
      - /bin/sh
      - -c
      - /usr/local/bin/spamhouse
  test:
    container_name: spamhouse_test
    build: 
      context: .
      target: final
    ports:
      - ${PORT}:${PORT}
    environment: 
      - DATA_SOURCE_NAME=/var/lib/sqlite/data/spamhouse.db
      - LOG_LEVEL=debug
      - PORT=${PORT}
    volumes:
      - data:/var/lib/sqlite/data
    command:
      - go test -v ./...

volumes:
  data:
    name: spamhouse-data
