// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IPAddressResult struct {
	Message string       `json:"message"`
	Node    []*IPAddress `json:"node"`
}

type Result struct {
	Status string    `json:"status"`
	Errors []*string `json:"errors"`
}
