version: '3.4'

services:

  spamhouse:
    image: spamhouse:latest
    container_name: spamhouse
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATA_SOURCE_NAME=/var/lib/sqlite/data/spamhouse.db
      - LOG_LEVEL=debug
      - PORT=${PORT}
    volumes:
      - data:/var/lib/sqlite/data
    command:
      - /bin/sh
      - -c
      - /usr/local/bin/spamhouse
volumes:
  data:
    name: spamhouse-data
